### ISSUE TITLE
TODO tasks for directx backend 

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#175]
### Task: Add Support for Additional Operators and Keywords in the DirectX Backend 
This task is focused on extending the functionality of the `DirectX backend` by adding support for several new tokens. These tokens must be added to the `lexer.py`, properly parsed in `parser.py`, and correctly translated in `directxtocrossglcodegen.py` to ensure full compatibility within the CrossTL ecosystem.
 

1.  Update lexer.py:

    Add new operators and keywords for each task as given . 

2. Update parser.py:

    Modify the parser to ensure that the new tokens are recognized and processed accurately.

3. Update directxtocrossglcodegen.py:

    Ensure that these tokens are properly translated from HLSL to CrossGL. Extend the logic for code generation to handle these new operators and keywords in DirectX shader code.
 
1. **Add Bitwise Operators:**
   - Purpose: Handle bitwise operations.
   - Tokens to Add:
        - [ ]  BITWISE_AND : &
        - [ ]  BITWISE_OR : |
        - [ ]  BITWISE_XOR : ^
        - [ ]  SHIFT_LEFT : <<
        - [ ]  SHIFT_RIGHT : >>

2. **Add Logical Operators:**
   - Purpose: Handle logical operations.
   - Tokens to Add:
      - [ ]  LOGICAL_AND" : &&
      - [ ]  LOGICAL_OR : ||

3. **Add Assignment Operators for Bitwise Operations:**
   - Purpose: Handle bitwise assignment operations.
   - Tokens to Add:
            - [ ]  ASSIGN_AND : &=
            - [ ]  ASSIGN_OR : |=
            - [ ]  ASSIGN_XOR : ^=

4. **Add Scalar Types (`half`, `double`):**
   - Purpose: Support scalar types in HLSL.
   - Tokens to Add:
           - [ ]  HALF : half
           - [ ]  DOUBLE : double

5. **Add `static` Keyword:**
   - Purpose: Handle the static keyword for defining static variables.
   - Token to Add:
     - [ ]  STATIC : static

6. **Add `control flow statement ` Keyword:**
   - Purpose: Handle the all control flow statements 
      - [ ] while loop
     - [ ] do-while loop 
     - [ ] switch statement 

6. **Add `pre processor ` Keyword:**
   - Purpose: Handle the pre processor in hlsl 
     - [ ]  #define pre processor 
     - [ ]  #ifdef / #ifndef / #endif
     - [ ] #include 
     - [ ] #pragma

This task is created for `Hacktoberfest` to welcome contributors to improve the project’s functionality by supporting these new tokens. Contributors should follow the contributing guidelines provided in the repository.

for and query feel free to ask on our [discord](https://discord.com/invite/uyRQKXhcyW) server we will be happy to help you out 😄

We welcome contributions and encourage developers of all levels to participate!

Cheers! 🎉
Good luck with CrossTL and Hacktoberfest! If you need further assistance, feel free to ask anytime. Happy coding!

**Comment by AxelB1011** [comment]
Can I take this one please?

**Comment by AcolyteOfTheWay** [comment]
@NripeshN please assign #188, #189 and #190

**Comment by NripeshN** [comment]
> @NripeshN Please do assign #188, #189 and #190 to me.

Hi @AcolyteOfTheWay,
Feel free to start working on these issues. You can create a PR(even if not completely completed) and mention in the description that is closes the issues related to the PR(eg. Closes #xyz #abc ...). Feel free to ask any further questions if you have any.

**Comment by madhurthareja** [comment]
@NripeshN Please assign this to me

**Comment by NripeshN** [comment]
> @NripeshN Please assign this to me

Hi @madhurthareja ,
Feel free to pick an issue you want and start working on the  PR(even if not completely completed) and mention in the description that it closes the issues related to the PR(eg. Closes #xyz #abc ...)

**Comment by annu3450** [comment]
@NripeshN Please assign #193 and #196

**Comment by Poojaa-M** [comment]
@NripeshN Please assign #190 to me

**Comment by tejatanush** [comment]
@NripeshN Please assign #194  and #197 task to me

**Comment by Sunny-DCosta** [comment]
@CrossGL-issue-bot assign me

**Comment by KripaAc** [comment]
@CrossGL-issue-bot assign me

**Comment by huntermarchi** [comment]
@NripeshN  Please assign #194 and #197 task to mr

**Comment by mannubhai1** [comment]
are there any unassigned tasks?

**Comment by mannubhai1** [comment]
@CrossGL-issue-bot assign me
