### ISSUE TITLE
ToDO for  translator frontend 

### ISSUE THREAD

**Issue by samthakur587** [CrossGL/crosstl#61]
- this task is to add support for `translator` frontend add token in `lexer` so it can also identify these tokens. for this task the one file  `crosstl/src/translator/lexer.py`

List of task 

- [x] #42 
- [x] #43 
- [x] #44 
- [x] #45 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49 
- [x] #50 
- [x] #51 
- [x] #52 
- [x] #53 
- [x] #54 
- [x] #55 
- [x] #56 
- [x] #57 
- [x] #58 
- [x] #59 
- [x] #60 

## how to assign task

- you can assign the task to  your self just comment down the name of task on the issue  which you want to work  we will be assign that task to you. 

- we are not limited to these task only feel free to create any issue weather it is `adding new feature` , `bug` some or some `fix` and start working on that .

for and query feel free to ask  on our [discord](https://discord.com/invite/uyRQKXhcyW) server we will be happy to help you out 😄 

Happy coding 🚀 

Thanks for contributing here 
sam

**Comment by Raghav-2903** [comment]
Hello 👋
@samthakur587 I would like to work on this issue

**Comment by samthakur587** [comment]
hii @Raghav-2903  select an issue from here comment down i'll assign that to you .like 

- [ ] #42

**Comment by Raghav-2903** [comment]
- [ ]  add BITWISE_AND Operators support at translator  frontend  #42
- [ ]  Add Bitwise OR  Token at translator frontend  #43
- [ ]  Add Bitwise XOR Token at translator frontend  #44
- [ ]  Add Bitwise NOT Token at translator frontend  #45
- [ ]  Add Bitwise Shift Left Token at translator frontend  #46
- [ ]  Add Bitwise Shift Right Token at translator frontend  #47
- [ ]  Add Assignment AND Token at translator frontend  #48

I would like to work on these issues if possible

**Comment by Raghav-2903** [comment]
- [ ] #42

- [ ] #43 

- [ ] #44 

- [ ] #45 

- [ ] #46 

- [ ] #47 

I would like to work on these issues if possible

**Comment by Proxihox** [comment]
Hi @samthakur587  I'd like to work on :

- #48
- #50
- #51 
- #52 
- #53 

The following Issues seem to already have been implemented in line numbers 46 and 47 respectively of `crosstl/src/translator/lexer.py`

- #56 
- #57

**Comment by samthakur587** [comment]
> Hi @samthakur587 I'd like to work on :
> 
>     * [Add `Assignment AND`  Token at translator frontend  #48](https://github.com/CrossGL/crosstl/issues/48)
> 
>     * [Add `Assignment OR`  Token at translator frontend  #50](https://github.com/CrossGL/crosstl/issues/50)
> 
>     * [Add `Assignment XOR`  Token at translator frontend  #51](https://github.com/CrossGL/crosstl/issues/51)
> 
>     * [Add `Assignment Modulus`  Token at translator frontend  #52](https://github.com/CrossGL/crosstl/issues/52)
> 
>     * [Add `Modulus`  Token at translator frontend  #53](https://github.com/CrossGL/crosstl/issues/53)
> 
> 
> The following Issues seem to already have been implemented in line numbers 46 and 47 respectively of `crosstl/src/translator/lexer.py`
> 
>     * [Add `Logical AND` Token at translator frontend  #56](https://github.com/CrossGL/crosstl/issues/56)
> 
>     * [Add `Logical OR`  Token at translator frontend  #57](https://github.com/CrossGL/crosstl/issues/57)

thanks @Proxihox for noticing   this i'll close these tasks as completed i'll assigned the other tasks to you.

**Comment by samthakur587** [comment]
> Hi @samthakur587 I will get assigned 42-47,right?

yes

**Comment by adarshkumar-prog** [comment]
Hii
I would like to work

**Comment by YOmaann** [comment]
Hi @samthakur587 . Please assign me some task. Preferably 48 - 50.

**Comment by Raghav-2903** [comment]
Hi @samthakur587, I have completed the tasks 42-47, Requesting you to look at the pull request I made

**Comment by rigved-desai** [comment]
Hi @samthakur587 can you please assign me these:
#58
#59

**Comment by praveencyber21** [comment]
Hello 
@samthakur587 I would like to work on this issue

**Comment by Deependra248** [comment]
Hii @samthakur587 can I please be assigned # 35 or #34

**Comment by shreekrsna** [comment]
hii @samthakur587 can I please be assigned #42 or #43

**Comment by siddharth0607** [comment]
@CrossGL-issue-bot assign me

**Comment by SatyamSingh8306** [comment]
i want to work on this issue if possible please assign it to me

**Comment by SatyamSingh8306** [comment]
@CrossGL-issue-bot assign me

**Comment by balakrishna1202** [comment]
@samthakur587 i will be working on #54 and #55

**Comment by krispycake** [comment]
I would like to work on this issue. Please assign it to me. add BITWISE_AND Operators support at translator  frontend  #42
